export const FETCH_LATEST_COMIC = 'FETCH_LATEST_COMIC';
export const FETCH_LATEST_COMIC_SUCCESS = 'FETCH_LATEST_COMIC_SUCCESS';
export const FETCH_RANDOM_COMIC = 'FETCH_RANDOM_COMIC';
export const FETCH_RANDOM_COMIC_SUCCESS = 'FETCH_COMIC_SUCCESS';
export const FETCH_COMIC_FAIL = 'FETCH_COMIC_FAIL';
export const UPDATE_RATE = 'UPDATE_RATE';
